# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/turbineyan/Downloads/WizQTClient-2.1.0

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/turbineyan/Downloads/WizQTClient-2.1.0

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/turbineyan/Downloads/WizQTClient-2.1.0/CMakeFiles /home/turbineyan/Downloads/WizQTClient-2.1.0/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/turbineyan/Downloads/WizQTClient-2.1.0/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cryptlib

# Build rule for target.
cryptlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cryptlib
.PHONY : cryptlib

# fast build rule for target.
cryptlib/fast:
	$(MAKE) -f lib/cryptopp/CMakeFiles/cryptlib.dir/build.make lib/cryptopp/CMakeFiles/cryptlib.dir/build
.PHONY : cryptlib/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f lib/clucene/CMakeFiles/uninstall.dir/build.make lib/clucene/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named clucene-shared-static

# Build rule for target.
clucene-shared-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clucene-shared-static
.PHONY : clucene-shared-static

# fast build rule for target.
clucene-shared-static/fast:
	$(MAKE) -f lib/clucene/src/shared/CMakeFiles/clucene-shared-static.dir/build.make lib/clucene/src/shared/CMakeFiles/clucene-shared-static.dir/build
.PHONY : clucene-shared-static/fast

#=============================================================================
# Target rules for targets named clucene-core-static

# Build rule for target.
clucene-core-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clucene-core-static
.PHONY : clucene-core-static

# fast build rule for target.
clucene-core-static/fast:
	$(MAKE) -f lib/clucene/src/core/CMakeFiles/clucene-core-static.dir/build.make lib/clucene/src/core/CMakeFiles/clucene-core-static.dir/build
.PHONY : clucene-core-static/fast

#=============================================================================
# Target rules for targets named cl_test

# Build rule for target.
cl_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cl_test
.PHONY : cl_test

# fast build rule for target.
cl_test/fast:
	$(MAKE) -f lib/clucene/src/test/CMakeFiles/cl_test.dir/build.make lib/clucene/src/test/CMakeFiles/cl_test.dir/build
.PHONY : cl_test/fast

#=============================================================================
# Target rules for targets named cl_test-ascii

# Build rule for target.
cl_test-ascii: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cl_test-ascii
.PHONY : cl_test-ascii

# fast build rule for target.
cl_test-ascii/fast:
	$(MAKE) -f lib/clucene/src/test/CMakeFiles/cl_test-ascii.dir/build.make lib/clucene/src/test/CMakeFiles/cl_test-ascii.dir/build
.PHONY : cl_test-ascii/fast

#=============================================================================
# Target rules for targets named cl_test-gcov

# Build rule for target.
cl_test-gcov: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cl_test-gcov
.PHONY : cl_test-gcov

# fast build rule for target.
cl_test-gcov/fast:
	$(MAKE) -f lib/clucene/src/test/CMakeFiles/cl_test-gcov.dir/build.make lib/clucene/src/test/CMakeFiles/cl_test-gcov.dir/build
.PHONY : cl_test-gcov/fast

#=============================================================================
# Target rules for targets named cl_test-mmap

# Build rule for target.
cl_test-mmap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cl_test-mmap
.PHONY : cl_test-mmap

# fast build rule for target.
cl_test-mmap/fast:
	$(MAKE) -f lib/clucene/src/test/CMakeFiles/cl_test-mmap.dir/build.make lib/clucene/src/test/CMakeFiles/cl_test-mmap.dir/build
.PHONY : cl_test-mmap/fast

#=============================================================================
# Target rules for targets named cl_test-namespace

# Build rule for target.
cl_test-namespace: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cl_test-namespace
.PHONY : cl_test-namespace

# fast build rule for target.
cl_test-namespace/fast:
	$(MAKE) -f lib/clucene/src/test/CMakeFiles/cl_test-namespace.dir/build.make lib/clucene/src/test/CMakeFiles/cl_test-namespace.dir/build
.PHONY : cl_test-namespace/fast

#=============================================================================
# Target rules for targets named cl_test-pedantic

# Build rule for target.
cl_test-pedantic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cl_test-pedantic
.PHONY : cl_test-pedantic

# fast build rule for target.
cl_test-pedantic/fast:
	$(MAKE) -f lib/clucene/src/test/CMakeFiles/cl_test-pedantic.dir/build.make lib/clucene/src/test/CMakeFiles/cl_test-pedantic.dir/build
.PHONY : cl_test-pedantic/fast

#=============================================================================
# Target rules for targets named cl_test-platform-charfuncs

# Build rule for target.
cl_test-platform-charfuncs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cl_test-platform-charfuncs
.PHONY : cl_test-platform-charfuncs

# fast build rule for target.
cl_test-platform-charfuncs/fast:
	$(MAKE) -f lib/clucene/src/test/CMakeFiles/cl_test-platform-charfuncs.dir/build.make lib/clucene/src/test/CMakeFiles/cl_test-platform-charfuncs.dir/build
.PHONY : cl_test-platform-charfuncs/fast

#=============================================================================
# Target rules for targets named cl_test-refcnt

# Build rule for target.
cl_test-refcnt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cl_test-refcnt
.PHONY : cl_test-refcnt

# fast build rule for target.
cl_test-refcnt/fast:
	$(MAKE) -f lib/clucene/src/test/CMakeFiles/cl_test-refcnt.dir/build.make lib/clucene/src/test/CMakeFiles/cl_test-refcnt.dir/build
.PHONY : cl_test-refcnt/fast

#=============================================================================
# Target rules for targets named cl_test-singlethreading

# Build rule for target.
cl_test-singlethreading: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cl_test-singlethreading
.PHONY : cl_test-singlethreading

# fast build rule for target.
cl_test-singlethreading/fast:
	$(MAKE) -f lib/clucene/src/test/CMakeFiles/cl_test-singlethreading.dir/build.make lib/clucene/src/test/CMakeFiles/cl_test-singlethreading.dir/build
.PHONY : cl_test-singlethreading/fast

#=============================================================================
# Target rules for targets named cl_test-static

# Build rule for target.
cl_test-static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cl_test-static
.PHONY : cl_test-static

# fast build rule for target.
cl_test-static/fast:
	$(MAKE) -f lib/clucene/src/test/CMakeFiles/cl_test-static.dir/build.make lib/clucene/src/test/CMakeFiles/cl_test-static.dir/build
.PHONY : cl_test-static/fast

#=============================================================================
# Target rules for targets named test-all

# Build rule for target.
test-all: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-all
.PHONY : test-all

# fast build rule for target.
test-all/fast:
	$(MAKE) -f lib/clucene/src/test/CMakeFiles/test-all.dir/build.make lib/clucene/src/test/CMakeFiles/test-all.dir/build
.PHONY : test-all/fast

#=============================================================================
# Target rules for targets named test-ascii

# Build rule for target.
test-ascii: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-ascii
.PHONY : test-ascii

# fast build rule for target.
test-ascii/fast:
	$(MAKE) -f lib/clucene/src/test/CMakeFiles/test-ascii.dir/build.make lib/clucene/src/test/CMakeFiles/test-ascii.dir/build
.PHONY : test-ascii/fast

#=============================================================================
# Target rules for targets named test-gcov

# Build rule for target.
test-gcov: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-gcov
.PHONY : test-gcov

# fast build rule for target.
test-gcov/fast:
	$(MAKE) -f lib/clucene/src/test/CMakeFiles/test-gcov.dir/build.make lib/clucene/src/test/CMakeFiles/test-gcov.dir/build
.PHONY : test-gcov/fast

#=============================================================================
# Target rules for targets named test-mmap

# Build rule for target.
test-mmap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-mmap
.PHONY : test-mmap

# fast build rule for target.
test-mmap/fast:
	$(MAKE) -f lib/clucene/src/test/CMakeFiles/test-mmap.dir/build.make lib/clucene/src/test/CMakeFiles/test-mmap.dir/build
.PHONY : test-mmap/fast

#=============================================================================
# Target rules for targets named test-namespace

# Build rule for target.
test-namespace: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-namespace
.PHONY : test-namespace

# fast build rule for target.
test-namespace/fast:
	$(MAKE) -f lib/clucene/src/test/CMakeFiles/test-namespace.dir/build.make lib/clucene/src/test/CMakeFiles/test-namespace.dir/build
.PHONY : test-namespace/fast

#=============================================================================
# Target rules for targets named test-pedantic

# Build rule for target.
test-pedantic: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-pedantic
.PHONY : test-pedantic

# fast build rule for target.
test-pedantic/fast:
	$(MAKE) -f lib/clucene/src/test/CMakeFiles/test-pedantic.dir/build.make lib/clucene/src/test/CMakeFiles/test-pedantic.dir/build
.PHONY : test-pedantic/fast

#=============================================================================
# Target rules for targets named test-platform-charfuncs

# Build rule for target.
test-platform-charfuncs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-platform-charfuncs
.PHONY : test-platform-charfuncs

# fast build rule for target.
test-platform-charfuncs/fast:
	$(MAKE) -f lib/clucene/src/test/CMakeFiles/test-platform-charfuncs.dir/build.make lib/clucene/src/test/CMakeFiles/test-platform-charfuncs.dir/build
.PHONY : test-platform-charfuncs/fast

#=============================================================================
# Target rules for targets named test-refcnt

# Build rule for target.
test-refcnt: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-refcnt
.PHONY : test-refcnt

# fast build rule for target.
test-refcnt/fast:
	$(MAKE) -f lib/clucene/src/test/CMakeFiles/test-refcnt.dir/build.make lib/clucene/src/test/CMakeFiles/test-refcnt.dir/build
.PHONY : test-refcnt/fast

#=============================================================================
# Target rules for targets named test-singlethreading

# Build rule for target.
test-singlethreading: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test-singlethreading
.PHONY : test-singlethreading

# fast build rule for target.
test-singlethreading/fast:
	$(MAKE) -f lib/clucene/src/test/CMakeFiles/test-singlethreading.dir/build.make lib/clucene/src/test/CMakeFiles/test-singlethreading.dir/build
.PHONY : test-singlethreading/fast

#=============================================================================
# Target rules for targets named cl_demo

# Build rule for target.
cl_demo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cl_demo
.PHONY : cl_demo

# fast build rule for target.
cl_demo/fast:
	$(MAKE) -f lib/clucene/src/demo/CMakeFiles/cl_demo.dir/build.make lib/clucene/src/demo/CMakeFiles/cl_demo.dir/build
.PHONY : cl_demo/fast

#=============================================================================
# Target rules for targets named quazip

# Build rule for target.
quazip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 quazip
.PHONY : quazip

# fast build rule for target.
quazip/fast:
	$(MAKE) -f lib/quazip/CMakeFiles/quazip.dir/build.make lib/quazip/CMakeFiles/quazip.dir/build
.PHONY : quazip/fast

#=============================================================================
# Target rules for targets named quazip_automoc

# Build rule for target.
quazip_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 quazip_automoc
.PHONY : quazip_automoc

# fast build rule for target.
quazip_automoc/fast:
	$(MAKE) -f lib/quazip/CMakeFiles/quazip_automoc.dir/build.make lib/quazip/CMakeFiles/quazip_automoc.dir/build
.PHONY : quazip_automoc/fast

#=============================================================================
# Target rules for targets named aggregation

# Build rule for target.
aggregation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aggregation
.PHONY : aggregation

# fast build rule for target.
aggregation/fast:
	$(MAKE) -f lib/aggregation/CMakeFiles/aggregation.dir/build.make lib/aggregation/CMakeFiles/aggregation.dir/build
.PHONY : aggregation/fast

#=============================================================================
# Target rules for targets named aggregation_automoc

# Build rule for target.
aggregation_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 aggregation_automoc
.PHONY : aggregation_automoc

# fast build rule for target.
aggregation_automoc/fast:
	$(MAKE) -f lib/aggregation/CMakeFiles/aggregation_automoc.dir/build.make lib/aggregation/CMakeFiles/aggregation_automoc.dir/build
.PHONY : aggregation_automoc/fast

#=============================================================================
# Target rules for targets named extensionsystem

# Build rule for target.
extensionsystem: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 extensionsystem
.PHONY : extensionsystem

# fast build rule for target.
extensionsystem/fast:
	$(MAKE) -f lib/extensionsystem/CMakeFiles/extensionsystem.dir/build.make lib/extensionsystem/CMakeFiles/extensionsystem.dir/build
.PHONY : extensionsystem/fast

#=============================================================================
# Target rules for targets named extensionsystem_automoc

# Build rule for target.
extensionsystem_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 extensionsystem_automoc
.PHONY : extensionsystem_automoc

# fast build rule for target.
extensionsystem_automoc/fast:
	$(MAKE) -f lib/extensionsystem/CMakeFiles/extensionsystem_automoc.dir/build.make lib/extensionsystem/CMakeFiles/extensionsystem_automoc.dir/build
.PHONY : extensionsystem_automoc/fast

#=============================================================================
# Target rules for targets named wiznote

# Build rule for target.
wiznote: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wiznote
.PHONY : wiznote

# fast build rule for target.
wiznote/fast:
	$(MAKE) -f src/CMakeFiles/wiznote.dir/build.make src/CMakeFiles/wiznote.dir/build
.PHONY : wiznote/fast

#=============================================================================
# Target rules for targets named wiznote_automoc

# Build rule for target.
wiznote_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wiznote_automoc
.PHONY : wiznote_automoc

# fast build rule for target.
wiznote_automoc/fast:
	$(MAKE) -f src/CMakeFiles/wiznote_automoc.dir/build.make src/CMakeFiles/wiznote_automoc.dir/build
.PHONY : wiznote_automoc/fast

#=============================================================================
# Target rules for targets named coreplugin

# Build rule for target.
coreplugin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coreplugin
.PHONY : coreplugin

# fast build rule for target.
coreplugin/fast:
	$(MAKE) -f src/plugins/coreplugin/CMakeFiles/coreplugin.dir/build.make src/plugins/coreplugin/CMakeFiles/coreplugin.dir/build
.PHONY : coreplugin/fast

#=============================================================================
# Target rules for targets named coreplugin_automoc

# Build rule for target.
coreplugin_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coreplugin_automoc
.PHONY : coreplugin_automoc

# fast build rule for target.
coreplugin_automoc/fast:
	$(MAKE) -f src/plugins/coreplugin/CMakeFiles/coreplugin_automoc.dir/build.make src/plugins/coreplugin/CMakeFiles/coreplugin_automoc.dir/build
.PHONY : coreplugin_automoc/fast

#=============================================================================
# Target rules for targets named helloworld

# Build rule for target.
helloworld: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 helloworld
.PHONY : helloworld

# fast build rule for target.
helloworld/fast:
	$(MAKE) -f src/plugins/helloworld/CMakeFiles/helloworld.dir/build.make src/plugins/helloworld/CMakeFiles/helloworld.dir/build
.PHONY : helloworld/fast

#=============================================================================
# Target rules for targets named helloworld_automoc

# Build rule for target.
helloworld_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 helloworld_automoc
.PHONY : helloworld_automoc

# fast build rule for target.
helloworld_automoc/fast:
	$(MAKE) -f src/plugins/helloworld/CMakeFiles/helloworld_automoc.dir/build.make src/plugins/helloworld/CMakeFiles/helloworld_automoc.dir/build
.PHONY : helloworld_automoc/fast

#=============================================================================
# Target rules for targets named markdown

# Build rule for target.
markdown: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 markdown
.PHONY : markdown

# fast build rule for target.
markdown/fast:
	$(MAKE) -f src/plugins/markdown/CMakeFiles/markdown.dir/build.make src/plugins/markdown/CMakeFiles/markdown.dir/build
.PHONY : markdown/fast

#=============================================================================
# Target rules for targets named markdown_automoc

# Build rule for target.
markdown_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 markdown_automoc
.PHONY : markdown_automoc

# fast build rule for target.
markdown_automoc/fast:
	$(MAKE) -f src/plugins/markdown/CMakeFiles/markdown_automoc.dir/build.make src/plugins/markdown/CMakeFiles/markdown_automoc.dir/build
.PHONY : markdown_automoc/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... cryptlib"
	@echo "... uninstall"
	@echo "... clucene-shared-static"
	@echo "... clucene-core-static"
	@echo "... cl_test"
	@echo "... cl_test-ascii"
	@echo "... cl_test-gcov"
	@echo "... cl_test-mmap"
	@echo "... cl_test-namespace"
	@echo "... cl_test-pedantic"
	@echo "... cl_test-platform-charfuncs"
	@echo "... cl_test-refcnt"
	@echo "... cl_test-singlethreading"
	@echo "... cl_test-static"
	@echo "... test-all"
	@echo "... test-ascii"
	@echo "... test-gcov"
	@echo "... test-mmap"
	@echo "... test-namespace"
	@echo "... test-pedantic"
	@echo "... test-platform-charfuncs"
	@echo "... test-refcnt"
	@echo "... test-singlethreading"
	@echo "... cl_demo"
	@echo "... quazip"
	@echo "... quazip_automoc"
	@echo "... aggregation"
	@echo "... aggregation_automoc"
	@echo "... extensionsystem"
	@echo "... extensionsystem_automoc"
	@echo "... wiznote"
	@echo "... wiznote_automoc"
	@echo "... coreplugin"
	@echo "... coreplugin_automoc"
	@echo "... helloworld"
	@echo "... helloworld_automoc"
	@echo "... markdown"
	@echo "... markdown_automoc"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

